### ISSUE TITLE
When starting calibration with a previous calibration file, button is mislabelled

### ISSUE THREAD

**Issue by iandol** [dcnieho/Titta#23]
Hi dee, we are loving the reload previous calibration. One very minor issue is the green `[calibrate (spacebar)]` button actually runs a validation:
![IMG_4548](https://user-images.githubusercontent.com/153905/79300026-24b4e900-7f18-11ea-8d0e-98790a64c599.jpeg)

Running a validation is fine for use, so we don't mind the functionality, but my operator thought he was doing a 1 point calibration each time then got confused it didn't seem to create menu entries so perhaps this can be rephrased to `[revalidate (spacebar)]`?

**Comment by dcnieho** [comment]
Hi Ian,

What happens if you press that calibrate button is that you actually start
a calibration, same as when you don't load in any previous calibration, or
when you arrive back at this setup screen from the validation result
screen. The way to only revalidate a previous calibration loaded in is to
not press calibrate at this screen, but previous calibrations, and to then
on press revalidate on the validation result screen that you get to.

Is this not what you are observing?

You can change the text on that button if you want by editing
settings.UI.button.setup.cal.string

Cheers,
Dee

**Comment by iandol** [comment]
I have our setup as 3 calibration points `[0.2 0.5], [0.5 0.5], [0.8 0.5]`, and my validation is set up for '[0.5 0.5]'. When I do a clean calibration (no previous cal file), `[calibrate (spacebar)]` uses the `[0.2 0.5], [0.5 0.5], [0.8 0.5]` points and then the validation `[0.5 0.5]` (4 points in total). 

BUT when we load a previous calibration, the `[calibrate (spacebar)]` button just presents `[0.5 0.5]` (1 point in total) — that's why I assume it is validating not calibrating (and IIRC no new entry is made in the [other calibrations] menu.

**Comment by dcnieho** [comment]
You are right. I did a shitty test yesterday, can reproduce now. Should be
fixed now

**Comment by dcnieho** [comment]
I added another commit that does the following: when loading a previous
calibration in call to Titta.calibrate(), setting settings.UI.startScreen =
0 now brings you straight to the validation result screen from which you
can revalidate. This means you can skip the setup screen and pressing on
"previous calibrations" there, if you want. NB, without a previous
calibration, settings.UI.startScreen = 0skips the setup screens and shows
the calibration dot display at once

**Comment by iandol** [comment]
Hi, when there is a previous calibration (line 731) but `startScreen` is true (line 754), `qGoToValidationViewer` is not defined and there is an error on line 809

https://github.com/dcnieho/Titta/blob/master/Titta.m#L731
https://github.com/dcnieho/Titta/blob/master/Titta.m#L809

**Comment by dcnieho** [comment]
Ugh! I am so sure i tested this, but obviously i haven't. Fixed, thanks for
the report!
