### ISSUE TITLE
DeInit creates wrong data type for obj.msgs

### ISSUE THREAD

**Issue by iandol** [dcnieho/Titta#27]
On construction you set: `obj.msgs = simpleVec(cell(1,2),1024);` -- but if we use this object and then then call `obj.deInit()` it gets set to `obj.msgs = [];` -- if we then use the same object again, it will crash as your `obj.sendMessage` etc. code expects this is a simpleVec class with methods like `append()`. I think you do expect us to be able to use the same object to connect/disconnect to an eyetracker right?

```
Dot indexing is not supported for variables of this type.

Error in Titta/sendMessage (line 1218)
            obj.msgs.append({time,str});
```

Simple fix is just make sure deInit assigns a simpleVec. MATLAB does allow you to define expected classes for object properties when you define them, which catches these types of errors. But this may potentially reduce future compatibility with octave (not sure if it supports a type system for class properties like MATLAB does?)

<https://www.mathworks.com/help/matlab/matlab_oop/property-size-and-class-validation.html#bvklfs7-1>
<https://www.mathworks.com/help/matlab/matlab_oop/property-validator-functions.html>

**Comment by dcnieho** [comment]
Thanks for the report! That was indeed the intention. I have a deja vu feeling with this bug, anyway, now its fixed with the simple fix you suggested. I think the nice solution is indeed to use these property validators, but that would not work with Octave and older versions of MATLAB (IIRC, this is a very recent addition).
