### ISSUE TITLE
Linux error on Ubuntu 20.04: glibcxx_3.4.29 not found

### ISSUE THREAD

**Issue by iandol** [dcnieho/Titta#40]
Hi Dee, we are currently still using Ubuntu 20.04 and with the latest Titta (after solving #38), we have the following error:

![Screenshot 2022-08-12 at 10 25 40](https://user-images.githubusercontent.com/153905/184598932-4ab39330-8f8c-4f36-84c9-ae60620be64e.png)

Do you build with 22.04 (**edit:** yes you do according to the readme in TittaMex subfolder)? We could recompile Titta on our system as one solution?

Another possible solution is here: https://askubuntu.com/questions/1393285/how-to-install-glibcxx-3-4-29-on-ubuntu-20-04 which suggests to use this PPA: https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/glibc —— but it is not recommended to mess with the libc libraries as many other things may break...

We will test this fix and update here, but I just wanted to mention this.

**Comment by dcnieho** [comment]
Hi Ian,

Yes, I built the latest one on 22.04, so that might be why. I did this
since, if i read and recall correctly, PTB has also moved to recommending
22.04. I'll add a note to the readme. Recompiling yourself should be easy
(just run /TittaMex/makeTittaMex.m), assuming the gcc that you have on your
system is new enough (see
https://github.com/dcnieho/Titta/tree/master/TittaMex).

**Comment by dcnieho** [comment]
Hi Ian, Did you resolve this?

**Comment by iandol** [comment]
We upgraded to 22.04 on all our systems so yes this is fixed, I'll close...
